image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '6'
    - nodejs_version: '4'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - cd src/AwesomeCMSCore/AwesomeCMSCore
  - npm install
matrix:
  fast_finish: true
build: off
shallow_clone: true
test_script:
  - npm run lint:js
  - npm run lint:style
cache:
  - '%APPDATA%\npm-cache'
build:
    project: src/AwesomeCMSCore/AwesomeCMSCore.sln
before_build:
  - cd src/AwesomeCMSCore 
  - dotnet restore
  - dotnet build