image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  nodejs_version: "8.10.0"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - cd src/AwesomeCMSCore/AwesomeCMSCore
  - npm install
matrix:
  fast_finish: true
build: off
shallow_clone: true
test_script:
  - npm run lint:js
  - npm run lint:style
  - cd ../
  - dotnet restore
  - dotnet build
cache:
  - '%APPDATA%\npm-cache'
