version: 2
jobs:
  build:
    working_directory: /src/AwesomeCMSCore
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore ./src/AwesomeCMSCore/AwesomeCMSCore.sln
      - run: dotnet build ./src/AwesomeCMSCore/AwesomeCMSCore.sln